FROM node:8.15.1-alpine
RUN apk add --no-cache curl 
RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app
COPY ./package*.json ./
#COPY package.json package-lock.json ./
USER node
RUN npm update
RUN npm ci --only=production

COPY --chown=node:node . .

EXPOSE 3000

CMD ["npm", "run", "start"]